"""clientes_borrado

Revision ID: 50022a5bf959
Revises: ecf8e8d89228
Create Date: 2026-08-11 10:55:07.993333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '50022a5bf959'
down_revision: Union[str, Sequence[str], None] = 'ecf8e8d89228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Ajustado a mano: el autogenerate no puso server_default, lo que
    falla contra una tabla `clientes` con filas existentes (columna
    NOT NULL sin valor por defecto). server_default=false rellena las
    filas ya existentes con el mismo valor por defecto que usa el
    dominio (Cliente.borrado: bool = False)."""
    op.add_column(
        'clientes',
        sa.Column('borrado', sa.Boolean(), nullable=False, server_default=sa.false()),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'borrado')
    # ### end Alembic commands ###
