"""contadores

Revision ID: cf201bd8f855
Revises: 8c8bf2f0d3c8
Create Date: 2026-08-11 07:44:34.852874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf201bd8f855'
down_revision: Union[str, Sequence[str], None] = '8c8bf2f0d3c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contadores',
    sa.Column('tipo_entidad', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tipo_entidad')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contadores')
    # ### end Alembic commands ###
